[[pages]]
path = "pages/quality.py"
name = "QualitÃ© des donnÃ©es"
icon = "ğŸ§¹"

[[pages]]
path = "pages/analysis.py"
name = "Analyse des clients"
icon = "ğŸ“Š"

[[pages]]
path = "pages/exploration.py"
name = "Exploration interactive"
icon = "ğŸ”"